<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {

            return $this->render('default/index.html.twig', [
                'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
            ]);
        } else {
            return $this->redirect($this->generateUrl('fos_user_security_login'));
        }
    }

    public function chartsAction(Request $request, $country)
    {
        if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            $countries = array (
                'BD' => 'Bangladesh',
                'BE' => 'Belgium',
                'BF' => 'BurkinaFaso',
                'BG' => 'Bulgaria',
                'BA' => 'BosniaandHerz.',
                'BN' => 'Brunei',
                'BO' => 'Bolivia',
                'JP' => 'Japan',
                'BI' => 'Burundi',
                'BJ' => 'Benin',
                'BT' => 'Bhutan',
                'JM' => 'Jamaica',
                'BW' => 'Botswana',
                'BR' => 'Brazil',
                'BS' => 'Bahamas',
                'BY' => 'Belarus',
                'BZ' => 'Belize',
                'RU' => 'Russia',
                'RW' => 'Rwanda',
                'RS' => 'Serbia',
                'TL' => 'Timor-Leste',
                'TM' => 'Turkmenistan',
                'TJ' => 'Tajikistan',
                'RO' => 'Romania',
                'GW' => 'Guinea-Bissau',
                'GT' => 'Guatemala',
                'GR' => 'Greece',
                'GQ' => 'Eq.Guinea',
                'GY' => 'Guyana',
                'GE' => 'Georgia',
                'GB' => 'United%20Kingdom',
                'GA' => 'Gabon',
                'GN' => 'Guinea',
                'GM' => 'Gambia',
                'GL' => 'Greenland',
                'GH' => 'Ghana',
                'OM' => 'Oman',
                'TN' => 'Tunisia',
                'JO' => 'Jordan',
                'HR' => 'Croatia',
                'HT' => 'Haiti',
                'HU' => 'Hungary',
                'HN' => 'Honduras',
                'PR' => 'PuertoRico',
                'PS' => 'Palestine',
                'PT' => 'Portugal',
                'PY' => 'Paraguay',
                'PA' => 'Panama',
                'PG' => 'PapuaNewGuinea',
                'PE' => 'Peru',
                'PK' => 'Pakistan',
                'PH' => 'Philippines',
                'PL' => 'Poland',
                'ZM' => 'Zambia',
                'EH' => 'W.Sahara',
                'EE' => 'Estonia',
                'EG' => 'Egypt',
                'ZA' => 'SouthAfrica',
                'EC' => 'Ecuador',
                'IT' => 'Italy',
                'VN' => 'Vietnam',
                'SB' => 'SolomonIs.',
                'ET' => 'Ethiopia',
                'SO' => 'Somalia',
                'ZW' => 'Zimbabwe',
                'ES' => 'Spain',
                'ER' => 'Eritrea',
                'ME' => 'Montenegro',
                'MD' => 'Moldova',
                'MG' => 'Madagascar',
                'MA' => 'Morocco',
                'UZ' => 'Uzbekistan',
                'MM' => 'Myanmar',
                'ML' => 'Mali',
                'MN' => 'Mongolia',
                'MK' => 'Macedonia',
                'MW' => 'Malawi',
                'MR' => 'Mauritania',
                'UG' => 'Uganda',
                'MY' => 'Malaysia',
                'MX' => 'Mexico',
                'IL' => 'Israel',
                'FR' => 'France',
                'XS' => 'Somaliland',
                'FI' => 'Finland',
                'FJ' => 'Fiji',
                'FK' => 'FalklandIs.',
                'NI' => 'Nicaragua',
                'NL' => 'Netherlands',
                'NO' => 'Norway',
                'NA' => 'Namibia',
                'VU' => 'Vanuatu',
                'NC' => 'NewCaledonia',
                'NE' => 'Niger',
                'NG' => 'Nigeria',
                'NZ' => 'NewZealand',
                'NP' => 'Nepal',
                'XK' => 'Kosovo',
                'CI' => 'Côted\'Ivoire',
                'CH' => 'Switzerland',
                'CO' => 'Colombia',
                'CN' => 'China',
                'CM' => 'Cameroon',
                'CL' => 'Chile',
                'XC' => 'N.Cyprus',
                'CA' => 'Canada',
                'CG' => 'Congo',
                'CF' => 'CentralAfricanRep.',
                'CD' => 'Dem.Rep.Congo',
                'CZ' => 'CzechRep.',
                'CY' => 'Cyprus',
                'CR' => 'CostaRica',
                'CU' => 'Cuba',
                'SZ' => 'Swaziland',
                'SY' => 'Syria',
                'KG' => 'Kyrgyzstan',
                'KE' => 'Kenya',
                'SS' => 'S.Sudan',
                'SR' => 'Suriname',
                'KH' => 'Cambodia',
                'SV' => 'ElSalvador',
                'SK' => 'Slovakia',
                'KR' => 'Korea',
                'SI' => 'Slovenia',
                'KP' => 'Dem.Rep.Korea',
                'KW' => 'Kuwait',
                'SN' => 'Senegal',
                'SL' => 'SierraLeone',
                'KZ' => 'Kazakhstan',
                'SA' => 'SaudiArabia',
                'SE' => 'Sweden',
                'SD' => 'Sudan',
                'DO' => 'DominicanRep.',
                'DJ' => 'Djibouti',
                'DK' => 'Denmark',
                'DE' => 'Germany',
                'YE' => 'Yemen',
                'DZ' => 'Algeria',
                'US' => 'UnitedStates',
                'UY' => 'Uruguay',
                'LB' => 'Lebanon',
                'LA' => 'LaoPDR',
                'TW' => 'Taiwan',
                'TT' => 'TrinidadandTobago',
                'TR' => 'Turkey',
                'LK' => 'SriLanka',
                'LV' => 'Latvia',
                'LT' => 'Lithuania',
                'LU' => 'Luxembourg',
                'LR' => 'Liberia',
                'LS' => 'Lesotho',
                'TH' => 'Thailand',
                'TF' => 'Fr.S.AntarcticLands',
                'TG' => 'Togo',
                'TD' => 'Chad',
                'LY' => 'Libya',
                'AE' => 'UnitedArabEmirates',
                'VE' => 'Venezuela',
                'AF' => 'Afghanistan',
                'IQ' => 'Iraq',
                'IS' => 'Iceland',
                'IR' => 'Iran',
                'AM' => 'Armenia',
                'AL' => 'Albania',
                'AO' => 'Angola',
                'AR' => 'Argentina',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'IN' => 'India',
                'TZ' => 'Tanzania',
                'AZ' => 'Azerbaijan',
                'IE' => 'Ireland',
                'ID' => 'Indonesia',
                'UA' => 'Ukraine',
                'QA' => 'Qatar',
                'MZ' => 'Mozambique',
            );

            $string = file_get_contents("http://api.population.io:80/1.0/population/".$countries[$country]."/2019-02-03");
            $json=json_decode($string,true);

            return $this->render('charts/country.html.twig', array(
                'json' => $countries[$country],
            ));
        } else {
            return $this->redirect($this->generateUrl('fos_user_security_login'));
        }
    }
}
