<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
        	$a = PHP_BINDIR;
            return $this->render('default/index.html.twig', array(
            	'a' => $a
            ));
        } else {
            return $this->redirect($this->generateUrl('fos_user_security_login'));
        }
    }

    public function chartsAction(Request $request, $country)
    {
        if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            $countries = array (
                'BD' => 'Bangladesh',
                'BE' => 'Belgium',
                'BF' => 'Burkina%20Faso',
                'BG' => 'Bulgaria',
                'BA' => 'Bosnia%20and%20Herzegovina',
                'BN' => 'Brunei',
                'BO' => 'Bolivia',
                'JP' => 'Japan',
                'BI' => 'Burundi',
                'BJ' => 'Benin',
                'BT' => 'Bhutan',
                'JM' => 'Jamaica',
                'BW' => 'Botswana',
                'BR' => 'Brazil',
                'BS' => 'Bahamas',
                'BY' => 'Belarus',
                'BZ' => 'Belize',
                'RU' => 'Russian%20Federation',
                'RW' => 'Rwanda',
                'RS' => 'Serbia',
                'TL' => 'Timor-Leste',
                'TM' => 'Turkmenistan',
                'TJ' => 'Tajikistan',
                'RO' => 'Romania',
                'GW' => 'Guinea-Bissau',
                'GT' => 'Guatemala',
                'GR' => 'Greece',
                'GQ' => 'Equatorial%20Guinea',
                'GY' => 'Guyana',
                'GE' => 'Georgia',
                'GB' => 'United%20Kingdom',
                'GA' => 'Gabon',
                'GN' => 'Guinea',
                'GM' => 'Gambia',
                'GL' => 'Greenland',
                'GH' => 'Ghana',
                'OM' => 'Oman',
                'TN' => 'Tunisia',
                'JO' => 'Jordan',
                'HR' => 'Croatia',
                'HT' => 'Haiti',
                'HU' => 'Hungary',
                'HN' => 'Honduras',
                'PR' => 'Puerto%20Rico',
                'PS' => 'Palestine',
                'PT' => 'Portugal',
                'PY' => 'Paraguay',
                'PA' => 'Panama',
                'PG' => 'Papua%20New%20Guinea',
                'PE' => 'Peru',
                'PK' => 'Pakistan',
                'PH' => 'Philippines',
                'PL' => 'Poland',
                'ZM' => 'Zambia',
                'EH' => 'Western%20Sahara',
                'EE' => 'Estonia',
                'EG' => 'Egypt',
                'ZA' => 'South%20Africa',
                'EC' => 'Ecuador',
                'IT' => 'Italy',
                'VN' => 'Vietnam',
                'SB' => 'Solomon%20Islands',
                'ET' => 'Ethiopia',
                'SO' => 'Somalia',
                'ZW' => 'Zimbabwe',
                'ES' => 'Spain',
                'ER' => 'Eritrea',
                'ME' => 'Montenegro',
                'MD' => 'Moldova',
                'MG' => 'Madagascar',
                'MA' => 'Morocco',
                'UZ' => 'Uzbekistan',
                'MM' => 'Myanmar',
                'ML' => 'Mali',
                'MN' => 'Mongolia',
                'MK' => 'Macedonia',
                'MW' => 'Malawi',
                'MR' => 'Mauritania',
                'UG' => 'Uganda',
                'MY' => 'Malaysia',
                'MX' => 'Mexico',
                'IL' => 'Israel',
                'FR' => 'France',
                'FI' => 'Finland',
                'FJ' => 'Fiji',
                'FK' => 'Falkland%20Islands',
                'NI' => 'Nicaragua',
                'NL' => 'Netherlands',
                'NO' => 'Norway',
                'NA' => 'Namibia',
                'VU' => 'Vanuatu',
                'NC' => 'New%20Caledonia',
                'NE' => 'Niger',
                'NG' => 'Nigeria',
                'NZ' => 'New%20Zealand',
                'NP' => 'Nepal',
                'XK' => 'Kosovo',
                'CI' => 'Cote-d-Ivoire',
                'CH' => 'Switzerland',
                'CO' => 'Colombia',
                'CN' => 'China',
                'CM' => 'Cameroon',
                'CL' => 'Chile',
                'XC' => 'N.Cyprus',
                'CA' => 'Canada',
                'CG' => 'Congo',
                'CF' => 'Central%20African%20Republic',
                'CD' => 'Dem%20Rep%20of%20Congo',
                'CZ' => 'Czech%20Republic',
                'CY' => 'Cyprus',
                'CR' => 'Costa%20Rica',
                'CU' => 'Cuba',
                'SZ' => 'Swaziland',
                'SY' => 'Syria',
                'KG' => 'Kyrgyzstan',
                'KE' => 'Kenya',
                'SS' => 'South%20Sudan',
                'SR' => 'Suriname',
                'KH' => 'Cambodia',
                'SV' => 'El%20Salvador',
                'SK' => 'Slovakia',
                'KR' => 'Rep%20of%20Korea',
                'SI' => 'Slovenia',
                'KP' => 'Dem%20Peoples%20Rep%20of%20Korea',
                'KW' => 'Kuwait',
                'SN' => 'Senegal',
                'SL' => 'Sierra%20Leone',
                'KZ' => 'Kazakhstan',
                'SA' => 'Saudi%20Arabia',
                'SE' => 'Sweden',
                'SD' => 'Sudan',
                'DO' => 'Dominican%20Republic',
                'DJ' => 'Djibouti',
                'DK' => 'Denmark',
                'DE' => 'Germany',
                'YE' => 'Yemen',
                'DZ' => 'Algeria',
                'US' => 'United%20States',
                'UY' => 'Uruguay',
                'LB' => 'Lebanon',
                'LA' => 'Lao%20PDR',
                'TW' => 'Taiwan',
                'TT' => 'Trinidad%20and%20Tobago',
                'TR' => 'Turkey',
                'LK' => 'Sri%20Lanka',
                'LV' => 'Latvia',
                'LT' => 'Lithuania',
                'LU' => 'Luxembourg',
                'LR' => 'Liberia',
                'LS' => 'Lesotho',
                'TH' => 'Thailand',
                'TF' => 'Fr.S.AntarcticLands',
                'TG' => 'Togo',
                'TD' => 'Chad',
                'LY' => 'Libya',
                'AE' => 'United%20Arab%20Emirates',
                'VE' => 'RB-de-Venezuela',
                'AF' => 'Afghanistan',
                'IQ' => 'Iraq',
                'IS' => 'Iceland',
                'IR' => 'Islamic%20Republic%20of%20Iran',
                'AM' => 'Armenia',
                'AL' => 'Albania',
                'AO' => 'Angola',
                'AR' => 'Argentina',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'IN' => 'India',
                'TZ' => 'Tanzania',
                'AZ' => 'Azerbaijan',
                'IE' => 'Ireland',
                'ID' => 'Indonesia',
                'UA' => 'Ukraine',
                'QA' => 'Qatar',
                'MZ' => 'Mozambique',
            );
            $countries2 = array (
                'BD' => 'BGD',
                'BE' => 'BEL',
                'BF' => 'BFA',
                'BG' => 'BGR',
                'BA' => 'BIH',
                'BN' => 'BRN',
                'BO' => 'BOL',
                'JP' => 'JPN',
                'BI' => 'BDI',
                'BJ' => 'BEN',
                'BT' => 'BTN',
                'JM' => 'JAM',
                'BW' => 'BWA',
                'BR' => 'BRA',
                'BS' => 'BHS',
                'BY' => 'BLR',
                'BZ' => 'BLZ',
                'RU' => 'RUS',
                'RW' => 'RWA',
                'RS' => 'SRB',
                'TL' => 'TLS',
                'TM' => 'TKM',
                'TJ' => 'TJK',
                'RO' => 'ROU',
                'GW' => 'GNB',
                'GT' => 'GTM',
                'GR' => 'GRC',
                'GQ' => 'GNQ',
                'GY' => 'GUY',
                'GE' => 'GEO',
                'GB' => 'GBR',
                'GA' => 'GAB',
                'GN' => 'GIN',
                'GM' => 'GMB',
                'GL' => 'GRL',
                'GH' => 'GHA',
                'OM' => 'OMN',
                'TN' => 'TUN',
                'JO' => 'JOR',
                'HR' => 'HRV',
                'HT' => 'HTI',
                'HU' => 'HUN',
                'HN' => 'HND',
                'PR' => 'PRI',
                'PS' => 'Palestine',
                'PT' => 'PRT',
                'PY' => 'PRY',
                'PA' => 'PAN',
                'PG' => 'PNG',
                'PE' => 'PER',
                'PK' => 'PAK',
                'PH' => 'PHL',
                'PL' => 'POL',
                'ZM' => 'ZMB',
                'EH' => 'Western%20Sahara',
                'EE' => 'EST',
                'EG' => 'EGY',
                'ZA' => 'ZAF',
                'EC' => 'ECU',
                'IT' => 'ITA',
                'VN' => 'VNM',
                'SB' => 'SLB',
                'ET' => 'ETH',
                'SO' => 'SOM',
                'ZW' => 'ZWE',
                'ES' => 'ESP',
                'ER' => 'ERI',
                'ME' => 'MNE',
                'MD' => 'MDA',
                'MG' => 'MDG',
                'MA' => 'MAR',
                'UZ' => 'UZB',
                'MM' => 'MMR',
                'ML' => 'MLI',
                'MN' => 'MNG',
                'MK' => 'MKD',
                'MW' => 'MWI',
                'MR' => 'MRT',
                'UG' => 'UGA',
                'MY' => 'MYS',
                'MX' => 'MEX',
                'IL' => 'ISR',
                'FR' => 'FRA',
                'FI' => 'FIN',
                'FJ' => 'FJI',
                'FK' => 'Falkland%20Islands',
                'NI' => 'NIC',
                'NL' => 'NLD',
                'NO' => 'NOR',
                'NA' => 'NAM',
                'VU' => 'VUT',
                'NC' => 'NCL',
                'NE' => 'NER',
                'NG' => 'NGA',
                'NZ' => 'NZL',
                'NP' => 'NPL',
                'XK' => 'XKX',
                'CI' => 'CIV',
                'CH' => 'CHE',
                'CO' => 'COL',
                'CN' => 'CHN',
                'CM' => 'CMR',
                'CL' => 'CHL',
                'XC' => 'N.Cyprus',
                'CA' => 'CAN',
                'CG' => 'COG',
                'CF' => 'CAF',
                'CD' => 'COD',
                'CZ' => 'CZE',
                'CY' => 'CYP',
                'CR' => 'CRI',
                'CU' => 'CUB',
                'SZ' => 'Swaziland',
                'SY' => 'SYR',
                'KG' => 'Kyrgyzstan',
                'KE' => 'KEN',
                'SS' => 'SSD',
                'SR' => 'SUR',
                'KH' => 'KHM',
                'SV' => 'SLV',
                'SK' => 'SVK',
                'KR' => 'KOR',
                'SI' => 'SVN',
                'KP' => 'PRK',
                'KW' => 'KWT',
                'SN' => 'SEN',
                'SL' => 'SLE',
                'KZ' => 'KAZ',
                'SA' => 'SAU',
                'SE' => 'SWE',
                'SD' => 'SDN',
                'DO' => 'DMA',
                'DJ' => 'DJI',
                'DK' => 'DNK',
                'DE' => 'DEU',
                'YE' => 'YEM',
                'DZ' => 'DZA',
                'US' => 'USA',
                'UY' => 'URY',
                'LB' => 'LBN',
                'LA' => 'LAO',
                'TW' => 'TWN',
                'TT' => 'TTO',
                'TR' => 'TUR',
                'LK' => 'LKA',
                'LV' => 'LVA',
                'LT' => 'LTU',
                'LU' => 'LUX',
                'LR' => 'LBR',
                'LS' => 'LSO',
                'TH' => 'THA',
                'TG' => 'TGO',
                'TD' => 'TCD',
                'LY' => 'LBY',
                'AE' => 'ARE',
                'VE' => 'VEN',
                'AF' => 'AFG',
                'IQ' => 'IRQ',
                'IS' => 'ISL',
                'IR' => 'IRN',
                'AM' => 'ARM',
                'AL' => 'ALB',
                'AO' => 'AGO',
                'AR' => 'ARG',
                'AU' => 'AUS',
                'AT' => 'AUT',
                'IN' => 'IND',
                'TZ' => 'TZA',
                'AZ' => 'AZE',
                'IE' => 'IRL',
                'ID' => 'IDN',
                'UA' => 'UKR',
                'QA' => 'QAT',
                'MZ' => 'MOZ',
            );
            $now = new \DateTime();
            // $string = file_get_contents("http://api.population.io:80/1.0/population/".$countries[$country]."/".$now->format("Y-m-d"));
            // $population=json_decode($string,true);

            // $string = file_get_contents("http://api.population.io:80/1.0/life-expectancy/total/female/".$countries[$country]."/1990-01-01");
            // $lifeExpectancyFemale = json_decode($string,true);

            // $string = file_get_contents("http://api.population.io:80/1.0/life-expectancy/total/male/".$countries[$country]."/1990-01-01");
            // $lifeExpectancyMale = json_decode($string,true);

            $string = file_get_contents("http://api.population.io:80/1.0/mortality-distribution/".$countries[$country]."/female/5y/today");
            $mortalityDistributionFemale = json_decode($string,true);

            $string = file_get_contents("http://api.population.io:80/1.0/mortality-distribution/".$countries[$country]."/male/5y/today");
            $mortalityDistributionMale = json_decode($string,true);

            $inputTotalPopulation = file_get_contents("https://api.worldbank.org/v2/sources/57/country/".$countries2[$country]."/series/SP.POP.TOTL/time/all/version/201809/data?per_page=6&format=json");
            $outputTotalPopulation = json_decode($inputTotalPopulation, true);

            $inputGDPcapita = file_get_contents("https://api.worldbank.org/v2/sources/57/country/".$countries2[$country]."/series/NY.GDP.PCAP.CD/time/all/version/201809/data?per_page=13&format=json");
            $outputGDPcapita = json_decode($inputGDPcapita, true);

            $inputLifeExpectancyFemale = file_get_contents("https://api.worldbank.org/v2/sources/57/country/".$countries2[$country]."/series/SP.DYN.LE00.FE.IN/time/all/version/201809/data?per_page=11&format=json");
            $outputLifeExpectancyFemale = json_decode($inputLifeExpectancyFemale, true);

            $inputLifeExpectancyMale = file_get_contents("https://api.worldbank.org/v2/sources/57/country/".$countries2[$country]."/series/SP.DYN.LE00.MA.IN/time/all/version/201809/data?per_page=11&format=json");
            $outputLifeExpectancyMale = json_decode($inputLifeExpectancyMale, true);


            $inputBirthRate= file_get_contents("https://api.worldbank.org/v2/sources/57/country//".$countries2[$country]."/series/SP.DYN.CBRT.IN/time/all/version/201809/data?per_page=50&format=json");
            $outputBirthRate = json_decode($inputBirthRate, true);


            $inputDeathRate= file_get_contents("https://api.worldbank.org/v2/sources/57/country//".$countries2[$country]."/series/SP.DYN.CDRT.IN/time/all/version/201809/data?per_page=50&format=json");
            $outputDeathRate = json_decode($inputDeathRate, true);

            $beautiful = str_replace("%20"," ",$countries[$country]);
            return $this->render('charts/country.html.twig', array(
                'country' => $beautiful,
                // 'population' => $population,
                // 'lifeExpectancyFemale' => $lifeExpectancyFemale,
                // 'lifeExpectancyMale' => $lifeExpectancyMale,
                'mortalityDistributionFemale' => $mortalityDistributionFemale,
                'mortalityDistributionMale' => $mortalityDistributionMale,
                'outputTotalPopulation' => $outputTotalPopulation,
                'outputGDPcapita' => $outputGDPcapita,
                'outputLifeExpectancyFemale' => $outputLifeExpectancyFemale,
                'outputLifeExpectancyMale' => $outputLifeExpectancyMale,
                'outputBirthRate' => $outputBirthRate,
                'outputDeathRate' => $outputDeathRate,
            ));
        } else {
            return $this->redirect($this->generateUrl('fos_user_security_login'));
        }
    }

    public function aboutAction(Request $request)
    {
        if ($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {

            return $this->render('about/about.html.twig');
        } else {
            return $this->redirect($this->generateUrl('fos_user_security_login'));
        }
    }
}
