app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_register:
  path:      /register
  defaults:  { _controller: AppBundle:Registration:register }

fos_user_security_login:
  path:      /login
  defaults:  { _controller: AppBundle:Security:login }


homepage:
  path:      /
  defaults:  { _controller: AppBundle:Default:index }

charts:
  path:      /countries/{country}
  defaults:  { _controller: AppBundle:Default:charts }

about:
  path:      /about
  defaults:  { _controller: AppBundle:Default:about }

privacy_policy:
  path:      /privacy-policy
  defaults:  { _controller: AppBundle:Default:privacy }